export const infos = [
  {
    num: 1,
    index: 8,
    matrícula: 'RA55000009',
    nome: 'Simael Palhares Borges Garcia',
    idade: 19,
    renda: 0,
    cor: 2,
    sexo: 1,
    ano_curso: 3,
    escola: 1,
    cod_curso: 9,
    logradouro: 'Rua Duque da Terceira',
    numero: 930,
    bairro: 'Jardim Maristela',
    cidade: 'São Paulo',
    uf: 'SP',
    cep: '02807-030',
    motivação: 10,
    pontos: 34,
  },
  {
    num: 2,
    index: 0,
    matrícula: 'RA55000001',
    nome: 'Aldelita Dinis',
    idade: 19,
    renda: 0,
    cor: 1,
    sexo: 2,
    ano_curso: 3,
    escola: 1,
    cod_curso: 3,
    logradouro: 'Rua Major Ari Gomes',
    numero: 118,
    bairro: 'Vila Mazzei',
    cidade: 'São Paulo',
    uf: 'SP',
    cep: '02309-050',
    motivação: 10,
    pontos: 33,
  },
  {
    num: 3,
    index: 1,
    matrícula: 'RA55000002',
    nome: 'Leudo Campelo  Ouro',
    idade: 19,
    renda: 0,
    cor: 1,
    sexo: 1,
    ano_curso: 3,
    escola: 1,
    cod_curso: 7,
    logradouro: 'Rua Caetano Mero',
    numero: 60,
    bairro: 'Vila Constança',
    cidade: 'São Paulo',
    uf: 'SP',
    cep: '04658-080',
    motivação: 10,
    pontos: 33,
  },
  {
    num: 4,
    index: 12,
    matrícula: 'RA55000013',
    nome: 'Namara Gago',
    idade: 19,
    renda: 0,
    cor: 1,
    sexo: 2,
    ano_curso: 3,
    escola: 1,
    cod_curso: 2,
    logradouro: 'Rua Silva Pinto',
    numero: 972,
    bairro: 'Bom Retiro',
    cidade: 'São Paulo',
    uf: 'SP',
    cep: '01126-010',
    motivação: 10,
    pontos: 33,
  },
  {
    num: 5,
    index: 10,
    matrícula: 'RA55000011',
    nome: 'Maggy Ramos Da Costa',
    idade: 19,
    renda: 0,
    cor: 1,
    sexo: 2,
    ano_curso: 3,
    escola: 1,
    cod_curso: 7,
    logradouro: 'Rua Monsenhor Salim',
    numero: 959,
    bairro: 'Itaim Paulista',
    cidade: 'São Paulo',
    uf: 'SP',
    cep: '08111-180',
    motivação: 10,
    pontos: 33,
  },
  {
    num: 6,
    index: 9,
    matrícula: 'RA55000010',
    nome: 'Dislaine Casalinho Vaz Imperial',
    idade: 19,
    renda: 0,
    cor: 1,
    sexo: 2,
    ano_curso: 3,
    escola: 1,
    cod_curso: 6,
    logradouro: 'Rua Vinte de Março',
    numero: 315,
    bairro: 'Jardim Felicidade (Zona Norte)',
    cidade: 'São Paulo',
    uf: 'SP',
    cep: '02326-115',
    motivação: 10,
    pontos: 33,
  },
  {
    num: 7,
    index: 14,
    matrícula: 'RA55000015',
    nome: 'Lucimare Olaio',
    idade: 19,
    renda: 0,
    cor: 1,
    sexo: 2,
    ano_curso: 3,
    escola: 1,
    cod_curso: 8,
    logradouro: 'Rua Sete de Abril',
    numero: 787,
    bairro: 'Centro',
    cidade: 'São Paulo',
    uf: 'SP',
    cep: '01044-902',
    motivação: 10,
    pontos: 33,
  },
  {
    num: 8,
    index: 5,
    matrícula: 'RA55000006',
    nome: 'Jailan Valverde Natal',
    idade: 19,
    renda: 0,
    cor: 1,
    sexo: 1,
    ano_curso: 3,
    escola: 1,
    cod_curso: 6,
    logradouro: 'Rua Marcos Freire',
    numero: 579,
    bairro: 'Jardim Nova Conquista',
    cidade: 'São Paulo',
    uf: 'SP',
    cep: '08346-580',
    motivação: 10,
    pontos: 33,
  },
  {
    num: 9,
    index: 4,
    matrícula: 'RA55000005',
    nome: 'Apolonia Arantes Ruas Pacheco',
    idade: 19,
    renda: 0,
    cor: 1,
    sexo: 2,
    ano_curso: 3,
    escola: 1,
    cod_curso: 5,
    logradouro: 'Rua Curruíra',
    numero: 550,
    bairro: 'Vila Aurora',
    cidade: 'São Paulo',
    uf: 'SP',
    cep: '05186-200',
    motivação: 10,
    pontos: 33,
  },
  {
    num: 10,
    index: 3,
    matrícula: 'RA55000004',
    nome: 'Clislene Cantanhede',
    idade: 19,
    renda: 0,
    cor: 1,
    sexo: 2,
    ano_curso: 3,
    escola: 1,
    cod_curso: 1,
    logradouro: 'Rua Caetano de Moura',
    numero: 216,
    bairro: 'Vila Nina',
    cidade: 'São Paulo',
    uf: 'SP',
    cep: '02833-060',
    motivação: 10,
    pontos: 33,
  },
  {
    num: 11,
    index: 6,
    matrícula: 'RA55000007',
    nome: 'Eliane Esparteiro Gorjão Mourato',
    idade: 19,
    renda: 0,
    cor: 1,
    sexo: 2,
    ano_curso: 3,
    escola: 1,
    cod_curso: 6,
    logradouro: 'Rua Vinte e Dois de Abril',
    numero: 329,
    bairro: 'Lajeado',
    cidade: 'São Paulo',
    uf: 'SP',
    cep: '08450-420',
    motivação: 10,
    pontos: 33,
  },
  {
    num: 12,
    index: 11,
    matrícula: 'RA55000012',
    nome: 'Ketlin Malho Mirandela',
    idade: 19,
    renda: 0,
    cor: 2,
    sexo: 2,
    ano_curso: 3,
    escola: 1,
    cod_curso: 7,
    logradouro: 'Avenida Duquesa de Goiás',
    numero: 792,
    bairro: 'Real Parque',
    cidade: 'São Paulo',
    uf: 'SP',
    cep: '05686-900',
    motivação: 9,
    pontos: 31,
  },
  {
    num: 13,
    index: 7,
    matrícula: 'RA55000008',
    nome: 'Gesiane Sintra Pederneiras Nolasco',
    idade: 19,
    renda: 0,
    cor: 1,
    sexo: 2,
    ano_curso: 3,
    escola: 1,
    cod_curso: 5,
    logradouro: 'Rua Quinze de Novembro',
    numero: 803,
    bairro: 'Cantinho do Céu',
    cidade: 'São Paulo',
    uf: 'SP',
    cep: '04849-527',
    motivação: 9,
    pontos: 30,
  },
  {
    num: 14,
    index: 16,
    matrícula: 'RA55000017',
    nome: 'Mateus Sarmento Nóbrega Félix',
    idade: 19,
    renda: 0,
    cor: 1,
    sexo: 1,
    ano_curso: 3,
    escola: 1,
    cod_curso: 9,
    logradouro: 'Rua João Pais',
    numero: 348,
    bairro: 'Jardim Petrópolis',
    cidade: 'São Paulo',
    uf: 'SP',
    cep: '04603-904',
    motivação: 9,
    pontos: 30,
  },
  {
    num: 15,
    index: 2,
    matrícula: 'RA55000003',
    nome: 'Geisemara Gonçalves',
    idade: 19,
    renda: 0,
    cor: 1,
    sexo: 2,
    ano_curso: 3,
    escola: 1,
    cod_curso: 1,
    logradouro: 'Rua Vinte e Um de Abril',
    numero: 334,
    bairro: 'Jardim Colibri',
    cidade: 'São Paulo',
    uf: 'SP',
    cep: '04855-620',
    motivação: 9,
    pontos: 30,
  },
  {
    num: 16,
    index: 17,
    matrícula: 'RA55000018',
    nome: 'Gleidiane Espírito Santo Marroquim Bulhosa',
    idade: 19,
    renda: 0,
    cor: 1,
    sexo: 2,
    ano_curso: 3,
    escola: 1,
    cod_curso: 6,
    logradouro: 'Avenida Agami',
    numero: 715,
    bairro: 'Moema',
    cidade: 'São Paulo',
    uf: 'SP',
    cep: '04522-001',
    motivação: 9,
    pontos: 30,
  },
  {
    num: 17,
    index: 18,
    matrícula: 'RA55000019',
    nome: 'Ardilis Cruz Canadas',
    idade: 19,
    renda: 0,
    cor: 1,
    sexo: 1,
    ano_curso: 3,
    escola: 1,
    cod_curso: 9,
    logradouro: 'Rua Nossa Senhora Aparecida',
    numero: 604,
    bairro: 'Jardim Felicidade (Zona Norte)',
    cidade: 'São Paulo',
    uf: 'SP',
    cep: '02326-105',
    motivação: 9,
    pontos: 30,
  },
  {
    num: 18,
    index: 15,
    matrícula: 'RA55000016',
    nome: 'Endeson Remígio',
    idade: 19,
    renda: 0,
    cor: 1,
    sexo: 1,
    ano_curso: 3,
    escola: 1,
    cod_curso: 7,
    logradouro: 'Rua Treze de Maio',
    numero: 917,
    bairro: 'Cantinho do Céu',
    cidade: 'São Paulo',
    uf: 'SP',
    cep: '04849-650',
    motivação: 9,
    pontos: 30,
  },
  {
    num: 19,
    index: 13,
    matrícula: 'RA55000014',
    nome: 'Regiano Pais Sabala Lemos',
    idade: 19,
    renda: 0,
    cor: 1,
    sexo: 1,
    ano_curso: 3,
    escola: 1,
    cod_curso: 2,
    logradouro: 'Rua Pedro Voss',
    numero: 58,
    bairro: 'Vila Carrão',
    cidade: 'São Paulo',
    uf: 'SP',
    cep: '03437-000',
    motivação: 9,
    pontos: 30,
  },
  {
    num: 20,
    index: 144,
    matrícula: 'RA55000145',
    nome: 'Generina Espargosa',
    idade: 19,
    renda: 1,
    cor: 2,
    sexo: 2,
    ano_curso: 3,
    escola: 2,
    cod_curso: 6,
    logradouro: 'Rua Pedro Barbosa',
    numero: 194,
    bairro: 'Jardim Marília',
    cidade: 'São Paulo',
    uf: 'SP',
    cep: '03579-130',
    motivação: 10,
    pontos: 29,
  },
];
